package superkey

import (
	"fmt"
	"regexp"
	"strings"
)

var (
	// guidPattern matches the 16 hex character GUID generated by generateGUID().
	guidPattern = regexp.MustCompile(`^[a-f0-9]{16}$`)

	// resourceNamePattern matches resource names created by the worker:
	// redhat-<app-basename>-<type>-<16-hex-guid>
	resourceNamePattern = regexp.MustCompile(`^redhat-[a-zA-Z0-9._/-]+-[a-f0-9]{16}$`)

	// policyArnPattern matches IAM policy ARNs for resources created by the worker.
	// Supports standard AWS and GovCloud partitions.
	policyArnPattern = regexp.MustCompile(`^arn:aws(-[a-z-]+)?:iam::\d+:policy/redhat-[a-zA-Z0-9._/-]+-[a-f0-9]{16}$`)
)

// ValidateDestroyRequest validates that a destroy request contains safe,
// expected resource names before allowing any AWS delete operations.
// This prevents untrusted Kafka message data from being used to delete
// arbitrary AWS resources in a customer's account.
func ValidateDestroyRequest(req *DestroyRequest) error {
	if req.GUID == "" {
		return fmt.Errorf("missing GUID in destroy request")
	}

	if !guidPattern.MatchString(req.GUID) {
		return fmt.Errorf("invalid GUID format: must be 16 hex characters")
	}

	return validateStepsCompleted(req.StepsCompleted, req.GUID)
}

// validateStepsCompleted validates that all resource identifiers in
// StepsCompleted match expected naming patterns and contain the correct GUID.
func validateStepsCompleted(steps map[string]map[string]string, guid string) error {
	for stepName, stepData := range steps {
		output, hasOutput := stepData["output"]
		if !hasOutput || output == "" {
			// Steps like bind_role have no output; nothing to validate.
			continue
		}

		switch stepName {
		case "s3":
			if err := validateResourceName(output, guid, "s3 bucket"); err != nil {
				return err
			}
		case "role":
			if err := validateResourceName(output, guid, "role"); err != nil {
				return err
			}
		case "policy":
			if err := validatePolicyArn(output, guid); err != nil {
				return err
			}
		case "cost_report":
			if err := validateContainsGUID(output, guid, "cost report"); err != nil {
				return err
			}
		default:
			// Unknown step type — require GUID presence as a minimum safety check.
			if err := validateContainsGUID(output, guid, stepName); err != nil {
				return err
			}
		}
	}

	return nil
}

// validateResourceName checks that a resource name matches the expected
// redhat-<app>-<type>-<guid> pattern and contains the correct GUID.
func validateResourceName(name, guid, resourceType string) error {
	if !strings.Contains(name, guid) {
		return fmt.Errorf("%s name %q does not contain expected GUID", resourceType, name)
	}

	if !resourceNamePattern.MatchString(name) {
		return fmt.Errorf("%s name %q does not match expected pattern (redhat-<app>-<type>-<guid>)", resourceType, name)
	}

	return nil
}

// validatePolicyArn checks that a policy ARN matches the expected
// arn:aws:iam::<account>:policy/redhat-<app>-policy-<guid> pattern.
func validatePolicyArn(arn, guid string) error {
	if !strings.Contains(arn, guid) {
		return fmt.Errorf("policy ARN %q does not contain expected GUID", arn)
	}

	if !policyArnPattern.MatchString(arn) {
		return fmt.Errorf("policy ARN %q does not match expected pattern", arn)
	}

	return nil
}

// validateContainsGUID checks that a resource identifier at minimum contains
// the expected GUID, providing a baseline safety check for resource types
// whose naming format may vary.
func validateContainsGUID(name, guid, resourceType string) error {
	if !strings.Contains(name, guid) {
		return fmt.Errorf("%s name %q does not contain expected GUID", resourceType, name)
	}

	return nil
}
